### ISSUE TITLE
Convention psr12

### ISSUE THREAD

**Issue by bernard-ng** [patrick-Mukendi/treaning#1]
Très bien, pour améliorer la lisibilité de ton code je te recommande de lire les conventions psr12 que tu peux trouver sur php fig 

Ça t'aider à mieux écrire tes scripts mais sinon à part les erreurs de syntaxe et le lien qui ne sont pas bon c'est okay ✅

**Comment by patrick-Mukendi** [comment]
Merci beaucoup de la remarque.
je vais améliorer ça.

Le mar. 4 juin 2024 à 03:15, Bernard Ngandu ***@***.***> a
écrit :
